# Generated by Django 4.0.4 on 2022-05-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='api.client')),
            ],
            options={
                'unique_together': {('name', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('sum', models.TextField()),
                ('date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='api.organization')),
            ],
            options={
                'unique_together': {('organization', 'number')},
            },
        ),
    ]
